# Permalinks
permalink:           pretty

# Setup
title:               rajankpaul
tagline:             'undergraduate electrical engineering student at USC'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://rajankpaul.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rajan Paul
  url:               https://twitter.com/rajankpaul
  email:             paulkrajan[at]gmail[dot]com

# Custom vars
version:             1.0.0
