# Permalinks
#permalink:           pretty

# Setup
title:               rajankpaul
tagline:             'fight on! ✌️'
description:         'Updates about my life'
url:                 https://rajankpaul.com
baseurl:             ""
paginate:            3

# About/contact
author:
  name:              Rajan Paul
  url:               https://twitter.com/rajankpaul
  email:             paulkrajan[at]gmail[dot]com

# Custom vars
version:             1.0.0
